# CI/CD: GitHub Actions workflow for automated linting on push/pull requests.
name: Lint # workflow name (shows up in GitHub Actions tab)

# GitHub will run this workflow on pushes and pull requests for the "main" (production) branch.
on:
    push:
        branches: [main] 
    pull_request:
        branches: [main]
    workflow_dispatch:


jobs:
    # Define a job, eslint, to run on the GitHub Ubuntu virtual machine.
    eslint:
        runs-on: ubuntu-latest

        steps:
            # Check out the repo code.
            - name: Checkout code
              uses: actions/checkout@v4

            # Install Node.js v22.14.0 in virtual environment with version 4 of setup-node in GitHub Action.
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.14.0'
                  cache: 'npm'

            # Install dependencies using specified package.json.
            - name: Install dependencies
              run: npm ci

            # Check if ESLint is running from a different working directory.
            # pwd shows current working directory. ls -la lists all files there. cat tsconfig.json prints file contents.
            - name: Debug working directory
              run: |
                pwd
                ls -la
                cat tsconfig.json

            # Run lint script.
            - name: Run ESLint
              run: npm run lint