# CI/CD: GitHub Actions workflow for automated linting on push/pull requests.
name: Lint # workflow name (shows up in GitHub Actions tab)

# GitHub will run this workflow on pushes and pull requests for the "main" (production) branch.
on:
    push:
        branches: [main] 
    pull_request:
        branches: [main]


jobs:
    # Define a job, eslint, to run on the GitHub Ubuntu virtual machine.
    eslint:
        runs-on: ubuntu-latest

        steps:
            # Check out the repo code.
            - name: Checkout code
              uses: actions/checkout@v3

            # Install Node.js v18 in virtual environment.
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            # Install dependencies using specified package.json.
            - name: Install dependencies
              run: npm ci

            # Run lint script.
            - name: Run ESLint
              run: npm run lint